apiVersion: v1
kind: Service
metadata:
  name: dotnetcoreapp-service
spec:
  type: NodePort
  selector:
    app: dotnetcoreapp 
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30008
        
